all:
	# empty

atomic:
	gcc atomic.c -o atomic.out
	./atomic.out

spinlock:
	gcc spinlock.c -o spinlock.out
	./spinlock.out

sema:
	gcc sema.c -o sema.out
	./sema.out

clean:
	rm -rf *.a *.out *.o *.s
