arp:
	gcc -o arp.out ARP-forge.c
	sudo ./arp.out
udp:
	gcc -o udp.out UDP-forge.c
	sudo ./udp.out
tcp:
	gcc -o tcp.out TCP-forge.c
	sudo ./tcp.out
icmp:
	gcc -o icmp.out ICMP-forge.c
	sudo ./icmp.out
clean:
	rm -rf *.out

