mutex:
	gcc -o mutex.out mutex.c

spinlock:
	gcc -o spinlock.out spinlock.c

producer-consumer:
	gcc -o producer-consumer.out producer-consumer.c

race_condition:
	gcc -o race_condition.out race_condition.c

clean:
	rm *.out
